### ISSUE TITLE
submodule capnprort may need to be updated to latest version

### ISSUE THREAD

**Issue by weikengchen** [pung-project/pung#1]
Pung uses capnproto. If the developer uses a newer version of GCC, it will cause this error message: 
```
In file included from ./src/capnp/generated-header-support.h:31:0,
                 from ./src/capnp/compiler/grammar.capnp.h:7,
                 from src/capnp/compiler/compiler.h:29,
                 from src/capnp/compiler/module-loader.h:29,
                 from src/capnp/compiler/module-loader.c++:22:
./src/capnp/layout.h:129:65: error: could not convert template argument ‘b’ from ‘bool’ to ‘capnp::Kind’
 template <typename T, bool b> struct ElementSizeForType<List<T, b>> {
                                                                 ^
./src/capnp/layout.h:129:66: error: template argument 1 is invalid
 template <typename T, bool b> struct ElementSizeForType<List<T, b>> {
```

This incompatibility is fixed in a newer version of capnproto. Thus, changing the submodule version in pung repo to the latest version would be helpful.

Thanks to the authors for bringing pung, an efficient **asynchronous** secure messaging system, to the world!

**Comment by sga001** [comment]
Thanks for this. I'm actually planning to release a newer version of Pung that uses [SealPIR](https://github.com/pung-project/sealpir) (which is more efficient than XPIR) and relies on [tarpc](https://github.com/google/tarpc) instead.

I'm happy to merge your changes in the meantime though.

**Comment by weikengchen** [comment]
Thanks Sebastian. Actually I cannot wait to see the new pung with S&P'18 optimization!

pung's batch retrieval is highly useful in anonymous messaging system where users must pad the number of messages to retrieve into a specific bound in order to hide access patterns.

**Comment by sga001** [comment]
Done. I updated capnp and XPIR to the latest versions.
